# Variables aleatorios e histogramas

Los histogramas permiten ver la distribuci√≥n de variables continuas. En el eje x van los valors que hay en el espacio de muestra, mientras que en el eje y va la frecuencia de cada uno de los datos.

In [5]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [10]:
df = pd.read_csv('subsample_isz.csv')

ValueError: The value of index_col couldn't be 'True'

In [9]:
df

,Unnamed: 0,cname,ccodealp,ht_region,gle_cgdpc,undp_hdi,imf_pop,wef_imort,who_alc2000,who_tobt,wdi_exph
0,0,Tuvalu,TUV,Pacific,3174.05000,NaN,0.011,NaN,1.34,NaN,16.536638
1,1,Liberia,LBR,SubSaharian,488.26999,0.427,NaN,53.599998,3.72,14.2,10.036333
2,2,Togo,TGO,SubSaharian,1036.28000,0.484,6.929,NaN,1.44,NaN,5.246877
3,3,Peru,PER,LatAm,9227.15040,0.737,30.809,14.100000,5.38,NaN,5.473035
4,4,Sao Tome and Principe,STP,SubSaharian,2150.55000,0.565,NaN,NaN,5.69,NaN,8.353466
...,...,...,...,...,...,...,...,...,...,...,...
92,92,Guinea,GIN,SubSaharian,993.83002,0.414,11.745,65.199997,0.22,NaN,5.644798
93,93,Belarus,BLR,EastEurope,17780.64100,0.798,9.468,NaN,13.94,27.9,5.687722
94,94,El Salvador,SLV,LatAm,332.26999,0.678,NaN,13.600000,2.52,NaN,6.772403
95,95,Cote d'Ivoire,CIV,SubSaharian,1354.29000,0.466,22.524,76.199997,3.15,NaN,5.716274
96,96,"Congo, Democratic Republic",COD,SubSaharian,324.16000,0.425,NaN,74.500000,1.82,NaN,4.328234